version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --providers.docker --api.insecure=true
    ports:
      # The HTTP port
      - "9090:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  apache_static:
    build: /docker-images/apache-php-image/.
    image: api/apache_php
    # Will launch 2 instances of this image
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache_static.rule=Host(`labo.api.ch`) && PathPrefix(`/`)"
      - "traefik.http.services.ajax.loadbalancer.sticky=true"
      - "traefik.http.services.apache_static.loadbalancer.sticky.cookie.name=session"

  express_dynamic:
    build: /docker-images/express-image/.
    image: api/express_pets
    # Will launch 2 instances of this image
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.express_dynamic.rule=Host(`labo.api.ch`) && Path(`/pets/`)"
      - "traefik.http.services.express_dynamic.loadbalancer.server.port=3000"
      - "traefik.http.routers.express_dynamic.middlewares=express_dynamic-replacepath"
      - "traefik.http.middlewares.express_dynamic-replacepath.replacepath.path=/"